# Generated by Django 2.2 on 2019-04-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('song_name', models.CharField(max_length=50, verbose_name='歌名')),
                ('song_singer', models.CharField(max_length=50, verbose_name='歌手')),
                ('song_time', models.CharField(max_length=10, verbose_name='时长')),
                ('song_album', models.CharField(max_length=50, verbose_name='专辑')),
                ('song_languages', models.CharField(max_length=20, verbose_name='语种')),
                ('song_type', models.CharField(max_length=20, verbose_name='类型')),
                ('song_release', models.CharField(max_length=20, verbose_name='发行时间')),
                ('song_img', models.CharField(max_length=20, verbose_name='歌曲图片')),
                ('song_lyrics', models.CharField(default='暂无歌词', max_length=50, verbose_name='歌词')),
                ('song_file', models.CharField(max_length=50, verbose_name='歌曲文件')),
            ],
            options={
                'verbose_name': '歌曲信息',
                'verbose_name_plural': '歌曲信息',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('dynamic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('dynamic_plays', models.IntegerField(verbose_name='播放次数')),
                ('dynamic_search', models.IntegerField(verbose_name='搜索次数')),
                ('is_loved', models.IntegerField(default=0, verbose_name='是否喜欢')),
                ('is_collected', models.IntegerField(default=0, verbose_name='是否收藏')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Song', verbose_name='歌名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '歌曲动态',
                'verbose_name_plural': '歌曲动态',
            },
        ),
    ]
